


describe('Fix error generated by application not by cypress', () => {
  Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  return false
})
  it('Fixing application error', () => {
    
    cy.visit('./static/index.html')
    cy.get('h1').should('have.text','Hacker Escape Rooms' )
  })
})
